import type { Product, Category } from './types';

export const CATEGORIES: Category[] = ['Electronics', 'Apparel', 'Books', 'Home Goods'];

export const PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Smart Home Hub',
    description: 'Control all your smart devices from one central hub. Supports voice commands and automation.',
    price: 99.99,
    category: 'Electronics',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 15,
  },
  {
    id: 'prod-2',
    name: 'Wireless Noise-Cancelling Headphones',
    description: 'Immerse yourself in music with these high-fidelity, noise-cancelling headphones.',
    price: 199.99,
    category: 'Electronics',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 8,
  },
  {
    id: 'prod-3',
    name: '4K Ultra HD Monitor',
    description: 'A 27-inch 4K monitor with stunning clarity and color accuracy, perfect for professionals.',
    price: 449.50,
    category: 'Electronics',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 5,
  },
  {
    id: 'prod-4',
    name: 'Mechanical Keyboard',
    description: 'A durable and responsive mechanical keyboard for the ultimate typing experience.',
    price: 120.00,
    category: 'Electronics',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 20,
  },
  {
    id: 'prod-5',
    name: 'Classic Leather Jacket',
    description: 'A timeless leather jacket made from 100% genuine leather. Stylish and durable.',
    price: 249.99,
    category: 'Apparel',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 12,
  },
  {
    id: 'prod-6',
    name: 'Modern Fit T-Shirt',
    description: 'A comfortable and stylish t-shirt made from premium cotton.',
    price: 29.99,
    category: 'Apparel',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 50,
  },
  {
    id: 'prod-7',
    name: 'Performance Running Shoes',
    description: 'Lightweight and breathable running shoes designed for maximum comfort and speed.',
    price: 130.00,
    category: 'Apparel',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 30,
  },
  {
    id: 'prod-8',
    name: 'Slim-Fit Chinos',
    description: 'Versatile slim-fit chinos perfect for both casual and formal occasions.',
    price: 75.00,
    category: 'Apparel',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 25,
  },
  {
    id: 'prod-9',
    name: 'The Art of Programming',
    description: 'A comprehensive guide to computer science fundamentals and software design.',
    price: 39.99,
    category: 'Books',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 40,
  },
  {
    id: 'prod-10',
    name: 'Sci-Fi Epic: Galaxy\'s End',
    description: 'An award-winning science fiction novel about the last human colony.',
    price: 19.99,
    category: 'Books',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 100,
  },
  {
    id: 'prod-11',
    name: 'Minimalist Coffee Table',
    description: 'A sleek and modern coffee table with a minimalist design, made from solid oak.',
    price: 299.00,
    category: 'Home Goods',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 10,
  },
  {
    id: 'prod-12',
    name: 'Ergonomic Office Chair',
    description: 'Improve your posture and comfort with this fully adjustable ergonomic office chair.',
    price: 350.00,
    category: 'Home Goods',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 0,
  },
];
