import type { Product, Category } from './types';

export const CATEGORIES: Category[] = [
  {
    name: 'Fashion',
    subcategories: ['Men\'s Apparel', 'Women\'s Apparel', 'Footwear', 'Accessories', 'Jewelry'],
  },
  {
    name: 'Home & Garden',
    subcategories: ['Furniture', 'Home Decor', 'Kitchen & Dining', 'Bedding & Bath', 'Gardening Tools', 'Outdoor Living'],
  },
  {
    name: 'Health & Beauty',
    subcategories: ['Skincare', 'Haircare', 'Makeup', 'Fragrances', 'Personal Care', 'Health Supplements'],
  },
  {
    name: 'Toys & Hobbies',
    subcategories: ['Action Figures', 'Board Games', 'Puzzles', 'Arts & Crafts', 'Collectibles', 'Remote Control'],
  },
  {
    name: 'Mother & Kids',
    subcategories: ['Baby Gear', 'Kids\' Clothing', 'Nursery', 'Diapering', 'Feeding', 'Strollers & Car Seats'],
  },
  {
    name: 'Eco-friendly',
    subcategories: ['Reusable Products', 'Sustainable Fashion', 'Organic Food', 'Green Home', 'Eco-friendly Electronics'],
  },
  {
    name: 'Furniture',
    subcategories: ['Living Room', 'Bedroom', 'Dining Room', 'Office Furniture', 'Outdoor Furniture', 'Mattresses'],
  },
  {
    name: 'Pet Supplies',
    subcategories: ['Dog Supplies', 'Cat Supplies', 'Fish Supplies', 'Bird Supplies', 'Small Animal Supplies', 'Pet Food'],
  },
  {
    name: 'Food & Drink',
    subcategories: ['Snacks', 'Beverages', 'Fresh Produce', 'Pantry Staples', 'Gourmet Food', 'Organic Food'],
  },
  {
    name: 'Gift & Gadgets',
    subcategories: ['Unique Gifts', 'Tech Gadgets', 'Novelty Items', 'Personalized Gifts', 'Experience Gifts'],
  },
  {
    name: 'Sports & Entertainment',
    subcategories: ['Sporting Goods', 'Fitness Equipment', 'Outdoor Recreation', 'Musical Instruments', 'Movies & TV', 'Video Games'],
  },
  {
    name: 'Mobile Phones & Accessories',
    subcategories: ['Smartphones', 'Cases & Covers', 'Chargers', 'Headphones', 'Screen Protectors', 'Smartwatches'],
  },
  {
    name: 'Electronics',
    subcategories: ['Computers', 'Laptops', 'Tables', 'Cameras', 'Audio', 'Video', 'Wearable Tech'],
  },
  {
    name: 'Computer & Office',
    subcategories: ['Laptops', 'Desktops', 'Monitors', 'Printers', 'Keyboards & Mice', 'Office Supplies', 'Networking'],
  },
  {
    name: 'Automobiles & Motorcycles',
    subcategories: ['Car Accessories', 'Motorcycle Parts', 'Car Electronics', 'Tires & Wheels', 'Automotive Tools', 'Performance Parts'],
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Smart Home Hub',
    description: 'Control all your smart devices from one central hub. Supports voice commands and automation.',
    price: 99.99,
    category: 'Electronics',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 15,
  },
  {
    id: 'prod-2',
    name: 'Wireless Noise-Cancelling Headphones',
    description: 'Immerse yourself in music with these high-fidelity, noise-cancelling headphones.',
    price: 199.99,
    category: 'Electronics',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 8,
  },
  {
    id: 'prod-3',
    name: '4K Ultra HD Monitor',
    description: 'A 27-inch 4K monitor with stunning clarity and color accuracy, perfect for professionals.',
    price: 449.50,
    category: 'Electronics',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 5,
  },
  {
    id: 'prod-4',
    name: 'Mechanical Keyboard',
    description: 'A durable and responsive mechanical keyboard for the ultimate typing experience.',
    price: 120.00,
    category: 'Computer & Office',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 20,
  },
  {
    id: 'prod-5',
    name: 'Classic Leather Jacket',
    description: 'A timeless leather jacket made from 100% genuine leather. Stylish and durable.',
    price: 249.99,
    category: 'Fashion',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 12,
  },
  {
    id: 'prod-6',
    name: 'Modern Fit T-Shirt',
    description: 'A comfortable and stylish t-shirt made from premium cotton.',
    price: 29.99,
    category: 'Fashion',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 50,
  },
  {
    id: 'prod-7',
    name: 'Performance Running Shoes',
    description: 'Lightweight and breathable running shoes designed for maximum comfort and speed.',
    price: 130.00,
    category: 'Fashion',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 30,
  },
  {
    id: 'prod-8',
    name: 'Slim-Fit Chinos',
    description: 'Versatile slim-fit chinos perfect for both casual and formal occasions.',
    price: 75.00,
    category: 'Fashion',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 25,
  },
  {
    id: 'prod-9',
    name: 'The Art of Programming',
    description: 'A comprehensive guide to computer science fundamentals and software design.',
    price: 39.99,
    category: 'Books', // Keeping this for now as it doesn\'t fit into the new categories directly
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 40,
  },
  {
    id: 'prod-10',
    name: 'Sci-Fi Epic: Galaxy\'s End',
    description: 'An award-winning science fiction novel about the last human colony.',
    price: 19.99,
    category: 'Books', // Keeping this for now
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 100,
  },
  {
    id: 'prod-11',
    name: 'Minimalist Coffee Table',
    description: 'A sleek and modern coffee table with a minimalist design, made from solid oak.',
    price: 299.00,
    category: 'Furniture',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 10,
  },
  {
    id: 'prod-12',
    name: 'Ergonomic Office Chair',
    description: 'Improve your posture and comfort with this fully adjustable ergonomic office chair.',
    price: 350.00,
    category: 'Furniture',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 0,
  },
  // New products for new categories
  {
    id: 'prod-13',
    name: 'Organic Facial Cleanser',
    description: 'Gentle organic cleanser for all skin types, deeply cleanses and nourishes.',
    price: 25.00,
    category: 'Health & Beauty',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 50,
  },
  {
    id: 'prod-14',
    name: 'Yoga Mat',
    description: 'High-density, non-slip yoga mat for all your fitness needs.',
    price: 35.00,
    category: 'Sports & Entertainment',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 40,
  },
  {
    id: 'prod-15',
    name: 'Plush Toy Bear',
    description: 'Super soft and cuddly plush bear, perfect for kids of all ages.',
    price: 15.00,
    category: 'Toys & Hobbies',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 80,
  },
  {
    id: 'prod-16',
    name: 'Eco-Friendly Reusable Water Bottle',
    description: 'Stay hydrated with this stylish and durable BPA-free reusable water bottle.',
    price: 18.00,
    category: 'Eco-friendly',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 100,
  },
  {
    id: 'prod-17',
    name: 'Gourmet Coffee Beans',
    description: 'A rich and aromatic blend of single-origin coffee beans from Ethiopia.',
    price: 12.50,
    category: 'Food & Drink',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 70,
  },
  {
    id: 'prod-18',
    name: 'Smartwatch',
    description: 'Track your fitness, receive notifications, and more with this advanced smartwatch.',
    price: 199.00,
    category: 'Gift & Gadgets',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 25,
  },
  {
    id: 'prod-19',
    name: 'Ergonomic Pet Bed',
    description: 'Orthopedic pet bed for maximum comfort for your furry friend.',
    price: 60.00,
    category: 'Pet Supplies',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 30,
  },
  {
    id: 'prod-20',
    name: 'Baby Diaper Bag',
    description: 'Spacious and stylish diaper bag with multiple compartments for all baby essentials.',
    price: 45.00,
    category: 'Mother & Kids',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 35,
  },
  {
    id: 'prod-21',
    name: 'Gardening Tool Set',
    description: 'Essential tools for every gardener, including trowel, cultivator, and pruner.',
    price: 55.00,
    category: 'Home & Garden',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 20,
  },
  {
    id: 'prod-22',
    name: 'Latest Smartphone Model',
    description: 'The newest smartphone with advanced camera features and long-lasting battery.',
    price: 899.00,
    category: 'Mobile Phones & Accessories',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 15,
  },
  {
    id: 'prod-23',
    name: 'Car Phone Mount',
    description: 'Universal car phone mount with strong grip and adjustable viewing angles.',
    price: 20.00,
    category: 'Automobiles & Motorcycles',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 60,
  },
  {
    id: 'prod-24',
    name: 'Gaming Console',
    description: 'Next-gen gaming console for immersive gaming experiences.',
    price: 499.99,
    category: 'Sports & Entertainment',
    imageUrl: 'https://placehold.co/600x400.png',
    stock: 10,
  },
];
